mtianyan_mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    environment:
      - MYSQL_PORT=3306  # cannot change this port to other number
      - MYSQL_DATABASE=vue_shop # name you want for the database
      - MYSQL_USER=root # change to whatever username you wantr
      - MYSQL_ROOT_PASSWORD=mtianyanroot #change to good root password
    ports:
      - "3309:3306"
    volumes:
      - "./db:/var/lib/mysql"


mtianyan_nginx:
  restart: always
  image: nginx
  ports:
    - "82:80"
  volumes:
    - ./conf/nginx_book.conf:/etc/nginx/conf.d/nginx_book.conf
  volumes_from:
    - mtianyan_book_store
  links:
    - mtianyan_book_store:web

mtianyan_book_store:
  restart: always
  build: .
  ports:
    - "8001:8000"
  volumes:
    - .:/VueDjangoFrameWorkShop
    - ./conf/uwsgi.ini:/etc/uwsgi.ini
  links:
    - mtianyan_mysql:mysql
  command: uwsgi -s :8000 -w VueDjangoFrameWorkShop.wsgi -p 3